export default {
  EQ: ['EQ', '等于', '='],
  NE: ['NE', '不等于', '!='],
  LK: ['LK', '模糊查询', 'LIKE %abc%'],
  NC: ['NC', '不包含', 'NOT LIKE %abc%'],
  LLK: ['LLK', '左匹配', 'LIKE abc%'],
  BN: ['BN', '不以什么开头', 'NOT LIKE abc%'],
  RLK: ['RLK', '右匹配', 'LIKE %abc'],
  BT: ['BT', 'BETWEEN', 'BETWEEN 1 AND 2'],
  GT: ['GT', '大于', '>'],
  LT: ['LT', '小于', '<'],
  GE: ['GE', '大等于', '>='],
  LE: ['LE', '小等于', '<='],
  IN: ['IN', '在其中', 'IN ( )'],
  BK: ['BK', '为空', "IS NULL OR ==''"],
  NB: ['NB', '不为空', "IS NOT NULL AND !=''"],
  NU: ['NU', '为NULL', 'IS NULL'],
  NN: ['NN', '不为NULL', 'IS NOT NULL'],
  PLT: ['PLT', '属性比较', '属性1 < 属性2'],
  PLE: ['PLE', '属性比较', '属性1 <= 属性2'],
  NOTIN: ['NOTIN', '不包含', 'NOT IN ()'],
};
